export const projects = [
  {
    id: 1,
    name: "Belahdod",
    category: "Mobile & Dashboard App | Graduation Project",
    tools: "Flutter, Dart, Figma",
    image: "/images/belahodod image.png",
  },
  {
    id: 2,
    name: "ecoTransferz",
    category: "Mobile & Dashboard Design | Freelancer",
    tools: "Figma",
    image: "/images/ecoTransferz image.png",
  },
  {
    id: 3,
    name: "Music App",
    category: "Mobile App Design | Personal Project",
    tools: "Figma",
    image: "/images/music app image.png",
  },
  {
    id: 4,
    name: "Syrian Tourism Authority Website & Dashboard",
    category: "Web & Dashboard Design | Company Project",
    tools: "Figma",
    image: "/images/Syrian Tourism Authority image.png",
  },
  {
    id: 5,
    name: "MediPharma",
    category: "Mobile App | University Project",
    tools: "Flutter, Dart, Figma",
    image: "/images/MEDIPHARMA image.png",
  },
  {
    id: 6,
    name: "Di-Va",
    category: "Social Media App | University Project",
    tools: "Flutter, Dart, Figma",
    image: "/images/Di-Va image.png",
  },
  {
    id: 7,
    name: "ESTRATIJIYA",
    category: "Dashboard Design | Freelancer",
    tools: "Figma",
    image: "/images/ESTRATIJIYA image.png",
  },
  {
    id: 8,
    name: "Disabled People App",
    category: "Mobile App Design | Freelancer",
    tools: "Figma",
    image: "/images/Disabled People image.png",
  },
  {
    id: 9,
    name: "Camera Booth",
    category: "Desktop & Dashboard Design | Company Project",
    tools: "Figma",
    image: "/images/Camera Booth image.png",
  },
  {
    id: 10,
    name: "Roza Clinic",
    category: "Mobile & Dashboard Design | Freelancer",
    tools: "Figma",
    image: "/images/Roza Clinic image.png",
  },
  {
    id: 11,
    name: "Syrian Judo Authority Website",
    category: "Web Design | Freelancer",
    tools: "Figma",
    image: "/images/Syrian Judo Authority Website image.png",
  },
  {
    id: 12,
    name: "Compiler Project",
    category: "Compiler | University Project",
    tools: "Java, ANTLR",
    image: "/images/Compiler Project image.png",
  },
  {
    id: 13,
    name: "Operating Systems Project",
    category: "Bash Scripting | University Project",
    tools: "Bash Script",
    image: "/images/Operating Systems Project image.png",
  },
];
